version: '3'
services:
  #menu:
  #  image: yokudlela/menu:menu-latest
  #  ports:
  #    - 8080:8080

  db:
    image: mariadb:10.1.34
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: yokudlela
      MYSQL_DATABASE: keycloak
      MYSQL_USER: yokudlela
      MYSQL_PASSWORD: yokudlela
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
      - ${PWD}/../../disks/sql:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "6080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=yokudlela
      - DB_VENDOR=mariadb
      - DB_USER=yokudlela
      - DB_PASSWORD=yokudlela
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ${PWD}/realm-export.json:/tmp/example-realm.json
    depends_on:
      - db
