version: '3'
services:
  #menu:
  #  image: yokudlela/menu:menu-latest
  #  ports:
  #    - 8080:8080
  db:
    image: mariadb:10.1.34
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: yokudlela
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
      - ${PWD}/../../disks/sql:/var/lib/mysql
      - "${PWD}/init-db/iam.sql:/docker-entrypoint-initdb.d/1.sql:ro"
      - "${PWD}/init-db/table-service.sql:/docker-entrypoint-initdb.d/2.sql:ro"
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # docker inspect --format "{{json .State.Health }}" container_id

  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "6080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: yokudlela
      DB_VENDOR: mariadb
      DB_USER: iam
      DB_PASSWORD: iam
      DB_ADDR: db
      DB_DATABASE: iam
      DB_PORT: 3306
      KEYCLOAK_IMPORT: /tmp/example-realm.json
    volumes:
      - ${PWD}/realm-export.json:/tmp/example-realm.json
      #depends_on:
      #db:
      #  condition: service_healthy
    links:
      - db